### ISSUE TITLE
Add an optional default rendered component for each step

### ISSUE THREAD

**Issue by Alex0jk** [stackbuilders/react-native-spotlight-tour#13]
When this feature was first introduced in Amira there was a component collect TourBox that served as a default layout for content that will be rendered in each step of the tour. It was used some way like this:
```
<TourBox {...RenderProps}  title="This is a header title">
  {contents}
</TourBox
```
The Tour Box included elements like a header and buttons to go forward or backwards in the steps.
I noticed that something like this is not in this library. While I understand that this is due to the fact that we want to have the most customizable implementation. I think that having a default element to render in each step will help with using the library and understanding it better.

Something I think that instead of having a component called tour box that the user can use, we could add some properties to the TourStep interface for customizing different elements of a default "TourBox" like the `styles of the next and back button`, `style of the title and the contents inside` the TourBox and also have a `property `for the user to have it's `own component` rendered in each step as we have right now.

This could work like the props in this library: https://github.com/Jacse/react-native-app-intro-slider

**Comment by JoseLion** [comment]
Resolved by #19
