### ISSUE TITLE
Possible performance issues on Android

### ISSUE THREAD

**Issue by Alex0jk** [stackbuilders/react-native-spotlight-tour#42]
After testing the library around I noticed that there is a possibility for a transition of being slow or laggy. This is an issue mostly in old android phones, but newer ones could present the issue to a lesser degree.

I wonder, what could be done to improve the performance of the animations.

**Comment by sibelly** [comment]
I did a demo inside my expo app and it slowed down the app significantly.

**Comment by JoseLion** [comment]
Thanks a lot for your feedback, @sibelly. I haven't tried it myself using Expo, but we can take a look. Can you please share the versions of `react`, `react-native`, and `react-native-svg` you used? Thanks!

**Comment by sibelly** [comment]
react -> 17.0.2
react-native -> 0.68.2
react-native-svg -> 12.3.0
expo -> ~45.0.0

**Comment by tragicmj** [comment]
Any updates on this issue @JoseLion ?

**Comment by JoseLion** [comment]
Sorry for the late response. We're on the final steps of a new release that solves a few issues, and performance in animations is among them. For the next release, we reworked the animation flow to make it more robust and include some react-based optimizations. You'll also be able to choose whether or not to use the native driver (on each OS) to run the animations, giving you more control to solve possible animation performance issues.

We're on the final steps ship this new release, so thank you for your patience and for using this library! 🙂

**Comment by JoseLion** [comment]
I'm happy to announce that v2.0.0 is out! It'd be great to get some feedback on its performance on Android devices on this new version. Thank you all in advance! 🙂

**Comment by JoseLion** [comment]
Closing since the issue is stale and the performance problems were resolved on v2.0.0. Please open a separate issue if anyone encounters this problem again.
