### ISSUE TITLE
Exception thrown while executing UI block (Chrome debugger)

### ISSUE THREAD

**Issue by nicolas-wl** [stackbuilders/react-native-spotlight-tour#53]
When starting the tour with chrome debugger open an error gets thrown:

Exception thrown while executing UI block: 'childNode' is a required parameter

![Simulator Screen Shot - iPhone 12 Pro - 2022-03-22 at 22 23 02](https://user-images.githubusercontent.com/59285722/159578422-5bdebb4f-4c31-465f-883c-c6e3a0045a85.png)

**Comment by chezhe** [comment]
same error here.

**Comment by JoseLion** [comment]
We just released v2.0.0 which tackled a big refactor on the animation flow. I wasn't able to reproduce the issue anymore on v2.0.0. @nicolas-wl @chezhe can you confirm if this is fixed for you too using v2? Thanks!

**Comment by JoseLion** [comment]
Closing for now as the Chrome debugger issues have disappeared on v2.
