### ISSUE TITLE
Document that react-native-spotlight-tour also works on react-native-web

### ISSUE THREAD

**Issue by MikkoSteerpath** [stackbuilders/react-native-spotlight-tour#62]
I've been playing around a bit with this on react-native-web and the library seems to work without issue there. This is useful info to anyone looking for a solution that supports ios, android and web, and imho should be highlighted on the home page.

**Comment by JoseLion** [comment]
That's awesome news! I think that would be a nice addition to the documentation. Thanks again for the report. PRs are welcome 🙂

**Comment by hugoxiong5** [comment]
Great library! I've been searching for an up-to-date React Native product tour for both native and web, and this works nicely. 

(There may be some positional issues; for me, the spotlight tooltip seems to auto position at the top left of the web browser, but I haven't fully implemented it yet, so not sure. Using react-native-spotlight-tour v2.0.0 and react-native-web 0.18.10.)

**Comment by JoseLion** [comment]
Documentation has been added and full support for react-native-web is available since [v3.0.0](https://github.com/stackbuilders/react-native-spotlight-tour/releases/tag/v3.0.0) release.
