### ISSUE TITLE
Warpping functional components in AttachStep doesn't seem to work

### ISSUE THREAD

**Issue by MikkoSteerpath** [stackbuilders/react-native-spotlight-tour#64]
Internally, AttachStep clones the child and attaches a ref to it so it can use measureInWindow when ever the layout changes. This seems to not work if the child component is a functional component as I got this error:

```Warning: Function components cannot be given refs. Attempts to access this ref will fail. Did you mean to use React.forwardRef()?```

**Comment by JoseLion** [comment]
Thanks a lot for the report! That's right, we rely on `measureInWindow` to know where the attached element is going to be rendered, so we can tell where the spotlight should be rendered as well. Function components do not have this such a native method or even a ref. To solve this we need to wrap them on a native `View` component so we can correctly measure their layout.

This is solved on PR #67, which will be present in the next release (as soon as the PR is merged). In the meantime, a workaround (and a way to avoid the extra View), is to use `React.forwardRef` on your functional component and pass the ref to a native element at the top:

```ts
const MyCustomComp = React.forwardRef((props, ref) => {

  return (
    <View ref={ref}>
      {/* ...rest of the component */}
    </View>
  );
});
```

I hope this helps 🙂
