### ISSUE TITLE
Android Layout Problem with 2.0

### ISSUE THREAD

**Issue by mjgalawork** [stackbuilders/react-native-spotlight-tour#77]
The 2.0 Version runs fine on iOS. But on Android i encountered a weird behavior. 

1 - 2 Seconds after the spot animation is finished, the TourStep View jumps to the top of the screen and then back to its right position. Very fast but visible. It happens on every transition (next/previous). If you stay on the step it does not jump again.

I disabled/enabled the native driver, no change.

The 1.0.2 version does not have this error.  

"react-native": "0.68.5"
"react-native-svg": "^12.4.0"

**Comment by JoseLion** [comment]
@mjgalawork thanks for reporting this issue. I was able to reproduce it and I'm currently working on a feature which also resolves the problem. I'll keep this thread posted 🙂

**Comment by livefuture009** [comment]
@JoseLion  I am getting same issue for only Android also. I have attached video for issue.


https://user-images.githubusercontent.com/36209712/215525300-e37036c8-1ebc-4c2d-a279-23d0ef145e56.mp4

After showing tutorial step and stay around 1 ~ 2 seconds, it will be jump fast...
But it's visible. Is there any way to fix it?

Thanks.

**Comment by JoseLion** [comment]
This should be solved by #78. Release coming soon, thanks for the patience 🙂

**Comment by JoseLion** [comment]
I'm glad to announce that we just released `v.2.1.0`, which fixes this issue plus adds a bunch of new features to the tours 🎉
