### ISSUE TITLE
Spotlight style/shape

### ISSUE THREAD

**Issue by nateguy** [stackbuilders/react-native-spotlight-tour#86]
Not really an issue, but is there a way to change the style/shape of the spotlight itself? I would like to make a square rather than cricle spotlight

**Comment by JoseLion** [comment]
This feature is available since [v3.0.0](https://github.com/stackbuilders/react-native-spotlight-tour/releases/tag/v3.0.0) release. A new `rectangle` shape has been added to the provider and each step configuration.

**Comment by sufian1999** [comment]
@JoseLion 
Why does the rectangle shape gives error?

![simulator_screenshot_B1DC908A-4678-48BA-AD0E-A49B2CBF9C65](https://github.com/user-attachments/assets/980168ed-cc4c-4e6c-a5b3-2df0722be299)
